### ISSUE TITLE
Tile data of panama is not displayed.

### ISSUE THREAD

**Issue by gsi-env** [globalmaps-vt/gmpa10vt#1]
https://hfu.github.io/globalmaps-vt-style/gmpa10vt.html#8/7.710/-80.859

**Comment by hfu** [comment]
This was due to the lack of enabling gh-pages for global maps-vt/gmpa10vt . Fixed.
<img width="949" alt="2017-03-24 18 37 35" src="https://cloud.githubusercontent.com/assets/18297/24288536/1bd2677c-10c1-11e7-9aaa-3d48207cce07.png">
